name: Release
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Godot_Opus-Common
          path: |
            ${{ github.workspace }}/bin/samples/**
            ${{ github.workspace }}/bin/addons/godot_opus/godot_opus.gdextension
            ${{ github.workspace }}/bin/addons/godot_opus/godot_opus.svg
          if-no-files-found: error
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: godot-opus
          merge-multiple: true
      - name: Delete draft release(s)
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        shell: sh
        run: zip -r "Godot_Opus.zip" godot-opus
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Godot Opus
          files: Godot_Opus.zip
          generate_release_notes: true
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
